@domain = http://127.0.0.1:8000

### Get Access Token
POST {{domain}}/login
Content-Type: application/json

{
    "username": "username",
    "password":"password"
}

### Ping server
GET {{domain}}/ping

{

}

### Get data
GET {{domain}}/users?offset=0&limit=10
Content-Type: application/json
Authorization: bearer eNi2VybmFtZSIsImV4cCI6MTY1OTI3MTQwMjg5M30.UeDgerwx3JWI66a-vZpdgjCEv93s_q-hllgO5A8E53Y

{

}

### New User

POST {{domain}}/user
Content-Type: application/json
Authorization: bearer eNi2VybmFtZSIsImV4cCI6MTY1OTI3MTQwMjg5M30.UeDgerwx3JWI66a-vZpdgjCEv93s_q-hllgO5A8E53Y


{
    "first_name": "doan",
    "last_name": "nguyen",
    "email": "doannq03@gmail.com",
    "birth_day": "2001/6/18"
}